name: objectory
version: 0.4.3-dev
author: Vadim Tsushko <vadimtsushko@gmail.com>
description: Object document mapper/persistency layer for server-side and browser apps
homepage: https://github.com/vadimtsushko/objectory
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  logging: ">=0.9.1 <0.10.0"
  logging_handlers: any
  console_log_handler: any
  mongo_dart:
    git: 'https://github.com/vadimtsushko/mongo_dart.git'
  mongo_dart_query: ">=0.1.14 <0.2.0"
  quiver: ">=0.19.0+1 <0.20.0"
dev_dependencies:
  args: 'any'
  hop: any
  stream: any
  test: 'any'
